name: Publish

runs:
  using: "composite"
  steps:

  - name: Download Artifacts
    uses: actions/download-artifact@v4
    with:
      pattern: packages-*
      merge-multiple: true
      path: ${{ github.workspace }}/packages


  - name: Download Prerequisites
    shell: bash
    run: |
      wget https://raw.githubusercontent.com/disorderedmaterials/scripts/master/update-release
      chmod u+x ./update-release

  - name: Publish on GitHub (Release)
    shell: bash
    run: |
      set -ex
      TAG=$(cat tag)
      VERSION=$(echo $TAG | sed -e "s/hdf5-//g" -e "s/_/./g")
      export GITHUB_TOKEN=${{ github.token }}
      ./update-release -r disorderedmaterials/hdf5 -t ${TAG} -u -n "HDF5 @ ${VERSION}" packages/*.zip
