parameters:
  - name: extraflags
    default: ''

steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.x'
  - script: |
      choco install -y mingw
    displayName: 'Install Prerequisites'
  - powershell: |
      wget https://support.hdfgroup.org/ftp/lib-external/szip/2.1.1/src/szip-2.1.1.tar.gz -O szip.tar.gz
      tar -zxvf szip.tar.gz
      Remove-Item szip.tar.gz
      $SZIP_DIR = Get-ChildItem -Directory ./szip-*
      mkdir build-szip
      $SZIP_INSTALL_DIR = (Get-ChildItem -Directory  ./build-szip).name + "/install"
      cd build-szip
      cmake $SZIP_DIR -G "MinGW Makefiles"  -DCMAKE_INSTALL_PREFIX:path=$SZIP_INSTALL_DIR
      cmake --build . --config Release
      cmake --install .
    displayName: 'Compile SZIP'
  - powershell: |
      wget https://github.com/madler/zlib/archive/refs/tags/v1.2.11.zip -O zlib.zip
      7z x zlib.zip
      Remove-Item zlib.zip
      $ZLIB_DIR = Get-ChildItem -Directory ./zlib-*
      mkdir build-zlib
      $ZLIB_INSTALL_DIR = (Get-ChildItem -Directory  ./build-zlib).name + "/install"
      cd build-zlib
      cmake $ZLIB_DIR -G "MinGW Makefiles" -DCMAKE_INSTALL_PREFIX:path=$ZLIB_INSTALL_DIR
      cmake --build . --config Release
      cmake --install .
    displayName: 'Compile ZLIB'
  - powershell: |
      $ErrorActionPreference = 'Stop'
      $TAG = Get-Content -Path ./tag
      echo "Tag is: "$TAG
      $HDF5_ZIP = "https://github.com/HDFGroup/hdf5/archive/refs/tags/" + $TAG + ".zip"
      echo $HDF5_ZIP
      wget $HDF5_ZIP -O hdf5.zip
      unzip hdf5.zip
      Remove-Item hdf5.zip
      $HDF5_DIR = Get-ChildItem -Directory ./hdf5-*
      echo "Source dir is: "$HDF5_DIR.name
    displayName: 'Download HDF5'
  - powershell: |
      $ErrorActionPreference = 'Stop'
      $TAG = Get-Content -Path ./tag
      $HDF5_DIR = Get-ChildItem -Directory ./hdf5-*
      $SZIP_INSTALL_DIR = (Get-ChildItem -Directory  ./build-szip).name + "/install"
      $ZLIB_INSTALL_DIR = (Get-ChildItem -Directory  ./build-zlib).name + "/install"
      mkdir build
      cd build
      cmake $HDF5_DIR -G "MinGW Makefiles" ${{ parameters.extraflags }} -DHDF5_BUILD_FORTRAN:bool=True -DHDF5_INSTALL_MOD_FORTRAN:bool=True -DHDF5_INSTALL_MOD_FORTRAN:bool=True -DHDF5_ENABLE_SZIP_SUPPORT:bool=True -DSZIP_DIR:path=$SZIP_INSTALL_DIR -DHDF5_ENABLE_Z_LIB_SUPPORT:bool=True -DZLIB_DIR:path=$ZLIB_INSTALL_DIR -DCMAKE_BUILD_TYPE:string=Release -DCMAKE_INSTALL_PREFIX:path=./$TAG
      cmake --build . --config Release
      cmake --install .
    displayName: 'Build'
