parameters:
  - name: extraflags
    default: ''

steps:
  - bash: |
      set -ex
      brew update-reset
      brew install ninja
    displayName: 'Install Prerequisites'
  - bash: |
      set -ex
      TAG=$(cat tag)
      echo "Tag is: ${TAG}"
      wget https://github.com/HDFGroup/hdf5/archive/refs/tags/${TAG}.zip -O hdf5.zip
      unzip hdf5.zip
      rm hdf5.zip
      HDF5_DIR=$(ls -d hdf5-*)
      echo "Source dir is: ${HDF5_DIR}"
    displayName: 'Download HDF5'
  - bash: |
      set -ex
      TAG=$(cat tag)
      HDF5_DIR=$(ls -d hdf5-*)
      mkdir build
      cd build
      cmake ../${HDF5_DIR} -G "Ninja" ${{ parameters.extraflags }} -DHDF5_BUILD_FORTRAN:bool=True -DHDF5_INSTALL_MOD_FORTRAN:bool=True -DHDF5_INSTALL_MOD_FORTRAN:bool=True -DHDF5_ENABLE_SZIP_SUPPORT:bool=True -DHDF5_ENABLE_Z_LIB_SUPPORT:bool=True -DCMAKE_BUILD_TYPE:string=Release -DCMAKE_INSTALL_PREFIX:path=./${TAG} -DCMAKE_Fortran_COMPILER:string="gfortran-9"
      ninja
      ninja install
    displayName: 'Build'
