parameters:
  - name: suffix
    default: 'unknown'
  - name: zipcommand
    default: "zip -9rv"

steps:
  - bash: |
      set -ex
      TAG=$(cat tag)
      HDF5_DIR=$(ls -d hdf5-*)
      echo "Source dir is: ${HDF5_DIR}"
      INSTALL_DIR="build/${TAG}"
      echo "Install dir is: ${INSTALL_DIR}"
      mkdir packages
      cd build
      ${{ parameters.zipcommand }} ${TAG}-${{ parameters.suffix }}.zip ${TAG}
      mv ${TAG}-${{ parameters.suffix }}.zip ../packages
    displayName: 'Create Archive'
