stages:
  - stage: 'create_release'
    condition: not(endsWith(variables['Build.SourceBranch'], 'pre'))
    displayName: 'Create Release'
    jobs:
      - job: 'release_gh'
        displayName: 'Create Versioned Release (GH)'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - checkout: self
            persistCredentials: true
          - bash: |
              wget https://raw.githubusercontent.com/disorderedmaterials/scripts/master/update-release
              chmod u+x ./update-release
            displayName: 'Install Prerequisites'
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              specificBuildWithTriggering: true
              downloadType: 'single'
              artifactName: 'linux-artifacts'
            displayName: 'Download Linux Artifacts'
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              specificBuildWithTriggering: true
              downloadType: 'single'
              artifactName: 'osx-artifacts'
            displayName: 'Download OSX Artifacts'
          - task: DownloadBuildArtifacts@0
            inputs:
              buildType: 'current'
              specificBuildWithTriggering: true
              downloadType: 'single'
              artifactName: 'windows-artifacts'
            displayName: 'Download Windows Artifacts'
          - bash: |
              set -ex
              TAG=$(cat tag)
              VERSION=$(echo $TAG | sed -e "s/hdf5-//g" -e "s/_/./g")
              ./update-release -r disorderedmaterials/hdf5 -t ${TAG} -u -n "HDF5 @ ${VERSION}" $(System.ArtifactsDirectory)/*-artifacts/*zip
            env:
              GITHUB_TOKEN: $(REPO_SECRET)
            displayName: 'Create Versioned Release (GitHub)'
